[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ce"

[deploy]
startCommand = ""
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 8
